apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  installation_tag: My Kiali
  istio_namespace: istio-system
  deployment:
    namespace: observability
    view_only_mode: false
  external_services:
    grafana:
      url: 'http://grafana-service.my-grafana-operator.svc:3000'
      in_cluster_url: 'http://grafana-service.my-grafana-operator.svc:3000'
    prometheus:
      #url: 'http://prometheus.istio-system.svc:9090'
      #in_cluster_url: 'http://prometheus.istio-system.svc:9090' 
      in_cluster_url: 'http://monitoring.istio-system.svc:9090' 
    tracing:
      #url: 'http://jaeger-all-in-one-inmemory-query.monitoring.svc:16686'
      #enable: true
      #in_cluster_url: 'http://jaeger-all-in-one-inmemory-query.monitoring.svc:16686/jaeger'
      in_cluster_url: 'http://tracing.istio-system/jaeger'
      #in_cluster_url: 'http://tracing.monitoring/jaeger'
      use_grpc: false
  server:
    web_root: /mykiali
