apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: blog
resources:
- namespace.yaml
- app_v1.yaml
- app_v2.yaml
- app_v3.yaml
- autoscaling.yaml
- gateway.yaml
- service_monitor.yaml
- traffic_splitting.yaml
namespace: teste
