apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-rule
  namespace: tcc
spec:
  host: app
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
  namespace: tcc
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway
  http:
    - match:
        - queryParams:
            version:
              exact: v2
      route:
        - destination:
            host: app
            subset: v2
          weight: 10
    - route:
        - destination:
            host: app
            subset: v1
          weight: 90  
      timeout: 10s      
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx,gateway-error,connect-failure,refused-stream
      fault:
        delay:
          percentage:
            value: 0.1
          fixedDelay: 5s
